#steps:
#
#- name: 'gcr.io/apszaz-dft-commons/dft-python'
#  args: ['run_requests.py']
#
#- name: gcr.io/apszaz-dft-commons/terraform
#  args:
#  - init
#  - terraform
#
#- name: gcr.io/apszaz-dft-commons/terraform
#  args:
#  - plan
#  - -var-file=terraform/common_params.tfvars
#  - terraform

# Decrypt the file containing the key
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=CLOUDBUILD-SECRETS
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
     IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Use git clone.
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:apsureda/env-request
  volumes:
  - name: 'ssh'
    path: /root/.ssh