steps:

- name: gcr.io/$PROJECT_ID/terraform
  args:
  - init
  - terraform

- name: gcr.io/$PROJECT_ID/terraform
  args:
  - apply
  - -var-file=terraform/common_params.tfvars
  - -auto-approve
  - terraform

timeout: 20m
