steps:

- name: 'ubuntu'
  args: ['python3', 'run_requests.py']

- name: gcr.io/apszaz-dft-commons/terraform
  args:
  - init
  - terraform

- name: gcr.io/apszaz-dft-commons/terraform
  args:
  - plan
  - -var-file=terraform/params.tfvars
  - -auto-approve
  - terraform

